# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jordi Berges
email: jordi.berges@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Jordi Berges and this is my blog, you will find any tech realted stuf
  that I find interesting or that I am working on.
host: 192.168.1.242
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jberges.github.io" # the base hostname & protocol for your site

github_username:  JBerges

# Build settings
markdown: kramdown
